#[source.crates-io]
#replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[build]
incremental = true
rustflags = ["-C", "symbol-mangling-version=v0"]

[rust]
debuginfo-level = 1

[alias]
prisma = "run -p prisma-cli"