[package]
name = "plntcycl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
tokio = { version = "1.37.0", features = ["full"] }
sea-orm = { version = "1.0.0-rc.3", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros"]}