[workspace]
members = [".", "prisma-cli"]

[package]
name = "planters_cycle"
version = "0.1.0"
edition = "2021"

[dependencies]
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11" }
serde = "1.0.201"

